-- ============================================================================
-- EMRC Website Database Schema Setup
-- ============================================================================
-- This script sets up the required tables, Row Level Security (RLS) policies,
-- and explicit SQL grants to address the Supabase breaking change where tables 
-- in the public schema are no longer exposed to the Data/GraphQL API automatically.
--
-- Run these statements in your Supabase project's SQL Editor.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Table Definitions
-- ----------------------------------------------------------------------------

-- Create news table
CREATE TABLE IF NOT EXISTS public.news (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  image_url text NOT NULL,
  url text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create committee table
CREATE TABLE IF NOT EXISTS public.committee (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  position text NOT NULL,
  photo_url text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create newsletter_subscribers table
CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create maintenance_requests table
CREATE TABLE IF NOT EXISTS public.maintenance_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  department text NOT NULL,
  location text NOT NULL,
  issue text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ----------------------------------------------------------------------------
-- 2. Row Level Security (RLS) Configuration
-- ----------------------------------------------------------------------------

ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.committee ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maintenance_requests ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------------------------
-- 3. RLS Policies
-- ----------------------------------------------------------------------------

-- news: Allow public read-only access (anon & authenticated roles)
CREATE POLICY "Allow public read access to news" ON public.news
  FOR SELECT TO anon, authenticated USING (true);

-- committee: Allow public read-only access (anon & authenticated roles)
CREATE POLICY "Allow public read access to committee" ON public.committee
  FOR SELECT TO anon, authenticated USING (true);

-- newsletter_subscribers: Allow anyone to verify existences/duplicates and insert new subscriptions
CREATE POLICY "Allow public select by anyone" ON public.newsletter_subscribers
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Allow public insert to newsletter_subscribers" ON public.newsletter_subscribers
  FOR INSERT TO anon, authenticated WITH CHECK (true);

-- maintenance_requests: Allow anyone to insert new requests
CREATE POLICY "Allow public insert to maintenance_requests" ON public.maintenance_requests
  FOR INSERT TO anon, authenticated WITH CHECK (true);

-- ----------------------------------------------------------------------------
-- 4. Database API Exposure Grants (Supabase Breaking Change Fix)
-- ----------------------------------------------------------------------------
-- Previously, Supabase automatically granted select/insert/update/delete 
-- permissions to API roles (anon, authenticated, service_role).
-- Under the new policy, we must explicitly grant the required privileges.

-- news: Grant SELECT to API roles
GRANT SELECT ON public.news TO anon, authenticated;
GRANT ALL ON public.news TO service_role;

-- committee: Grant SELECT to API roles
GRANT SELECT ON public.committee TO anon, authenticated;
GRANT ALL ON public.committee TO service_role;

-- newsletter_subscribers: Grant SELECT and INSERT to API roles (for subscriptions and duplicates check)
GRANT SELECT, INSERT ON public.newsletter_subscribers TO anon, authenticated;
GRANT ALL ON public.newsletter_subscribers TO service_role;

-- maintenance_requests: Grant INSERT to API roles (for submission of requests)
GRANT SELECT, INSERT ON public.maintenance_requests TO anon, authenticated;
GRANT ALL ON public.maintenance_requests TO service_role;
